# Site settings
title: Dr-Meza
description: "Traumatólogo"
baseurl: "/dr-meza"
url: "" # the name of your domain
logo_url: img/logo.png

# Hero
hero: 
    hero_img: main_1.jpg
    hero_title: Doctor Salvador Meza Velázquez
    hero_description: Traumatología y Ortopedia. Cirugía de Reconstrucción Articular

# Contact form
api_token: e4c566219137fd655099615d7c82550c

# Contact info
contact:
    phone: +52 422-312-2431
    emergency: XX XX XX
    email: contact@yoursite.com
    address: Calle Privada Ignacio Zaragoza 16A,Consultorio 216, Torre 2, Villas del Refugio, 75030 Santiago de Querétaro, Qro.

# Opening hours
monday_friday: 9:00 – 17:00
saturday: Cerrado
sunday: Cerrado

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Calle Privada Ignacio Zaragoza 16A,Consultorio 216, Torre 2, Villas del Refugio, 75030 Santiago de Querétaro, Qro.
    address_details: svg/min/logo.svg

# Social settings
facebook: https://www.facebook.com/drmezavelazquez/
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2020 Kecho - Todos los derechos reservados

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
